### ISSUE TITLE
A problem on Debian Buster

### ISSUE THREAD

**Issue by Vyacheslav-S** [Saiyato/volumio-rotary-encoder-plugin#22]
On Volumio 3 (beta Debian Buste), the plugin does not correctly install dependencies and does not work.
Сurrent beta Volumio 3 use the new nodejs v14.x engine.
Can you help?

**Comment by Saiyato** [comment]
Hi @Vyacheslav-S ,

What image did you use and on what platform are you running?
On a Pi2 I'm getting node v8.17 and the plugin works. According to the topic they reverted back to Node v8 in August 2020, you might want to move to image 3.015.

**Comment by Saiyato** [comment]
Btw, this is the topic I'm referring to: https://community.volumio.org/t/volumio-debian-buster-beta-raspi-images-debugging/11988
