### ISSUE TITLE
Will not install on Volumio 3

### ISSUE THREAD

**Issue by mm1ck** [Saiyato/volumio-rotary-encoder-plugin#23]
Are there any plans to make your excelent plugin compatiible with Volumio 3 ( now in RC stage)

**Comment by mm1ck** [comment]
volumio@volumio:~$ wget https://github.com/Saiyato/volumio-rotary-encoder-plugin/raw/master/volumio-rotary-encoder-plugin.zip
--2021-11-25 15:51:21--  https://github.com/Saiyato/volumio-rotary-encoder-plugin/raw/master/volumio-rotary-encoder-plugin.zip
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Saiyato/volumio-rotary-encoder-plugin/master/volumio-rotary-encoder-plugin.zip [following]
--2021-11-25 15:51:21--  https://raw.githubusercontent.com/Saiyato/volumio-rotary-encoder-plugin/master/volumio-rotary-encoder-plugin.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7808 (7.6K) [application/zip]
Saving to: 'volumio-rotary-encoder-plugin.zip'

volumio-rotary-encoder-plugin.zip       100%[============================================================================>]   7.62K  --.-KB/s    in 0.001s

2021-11-25 15:51:22 (8.93 MB/s) - 'volumio-rotary-encoder-plugin.zip' saved [7808/7808]

volumio@volumio:~$ sudo miniunzip volumio-rotary-encoder-plugin.zip -d ./rotary
MiniUnz 1.01b, demo of zLib + Unz package written by Gilles Vollant
more info at http://www.winimage.com/zLibDll/unzip.html

volumio-rotary-encoder-plugin.zip opened
 extracting: config.json
 extracting: install.sh
 extracting: UIConfig.json
 extracting: uninstall.sh
creating directory: i18n/
 extracting: i18n/strings_en.json
creating directory: options/
 extracting: options/buttonOptions.json
 extracting: options/detentOptions.json
 extracting: options/encodingOptions.json
 extracting: index.js
 extracting: package.json
volumio@volumio:~$ cd ./rotary
volumio@volumio:~/rotary$ volumio plugin install

This command will install the plugin on your device

Compressing the plugin
No modules found, running "npm install"
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)
gyp ERR! System Linux 5.4.83-v7l+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/volumio/rotary/node_modules/epoll
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epoll@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the epoll@1.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/volumio/.npm/_logs/2021-11-25T15_52_56_280Z-debug.log
Error installing node modules: Error: Command failed: /usr/bin/npm install --production
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)
gyp ERR! System Linux 5.4.83-v7l+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/volumio/rotary/node_modules/epoll
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epoll@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the epoll@1.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/volumio/.npm/_logs/2021-11-25T15_52_56_280Z-debug.log

/bin/mv: cannot stat '*.zip': No such file or directory
child_process.js:655
    throw err;
    ^

Error: Command failed: /bin/mv *.zip /tmp/plugins/rotaryencoder.zip
/bin/mv: cannot stat '*.zip': No such file or directory

    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at install (/volumio/pluginhelper.js:765:9)
    at Object.<anonymous> (/volumio/pluginhelper.js:860:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(56) [Uint8Array] [
       47,  98, 105, 110,  47, 109, 118,  58,  32,  99,
       97, 110, 110, 111, 116,  32, 115, 116,  97, 116,
       32,  39,  42,  46, 122, 105, 112,  39,  58,  32,
       78, 111,  32, 115, 117,  99, 104,  32, 102, 105,
      108, 101,  32, 111, 114,  32, 100, 105, 114, 101,
       99, 116, 111, 114, 121,  10
    ]
  ],
  pid: 1126,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(56) [Uint8Array] [
     47,  98, 105, 110,  47, 109, 118,  58,  32,  99,
     97, 110, 110, 111, 116,  32, 115, 116,  97, 116,
     32,  39,  42,  46, 122, 105, 112,  39,  58,  32,
     78, 111,  32, 115, 117,  99, 104,  32, 102, 105,
    108, 101,  32, 111, 114,  32, 100, 105, 114, 101,
     99, 116, 111, 114, 121,  10
  ]
}
volumio@volumio:~/rotary$

**Comment by Saiyato** [comment]
Unfortunately this is something in the Volumio image, I was unable to figure out why this fails... Someone else on the forum did figure out a workaround though: https://community.volumio.org/t/install-npm-module-problem/48949/9

It's nothing in the plugin itself, but the dependencies it needs to function. When the Volumio team adds it to the store, they typically prebuild all the dependencies (which solves this problem). :wink:
