### ISSUE TITLE
No sound after installing

### ISSUE THREAD

**Issue by hailogugo** [Saiyato/volumio-rotary-encoder-plugin#5]
Hi,
I use a Hifi Amp which will install like a HifiBerry amp.
When I use it without the rotary it work fine.
If i use it with rotary after installing i do not have any sound avaiable. Do anybody have an idea where it come from?

Thank you.

Hifi Amp
http://www.inno-maker.com/shop/rpi-hifi-amp/

Rotary is 
KY040

Software
Volumio 2.389

**Comment by Saiyato** [comment]
That is certainly weird, because installing the plugin does "nothing".
I just copies over the javascript files to the plugins directory.

Can you step-by-step tell me what you did? Every bit of information is potentially interesting, i.e.:

1. flash sd
2. boot up
3. configure I2S
4. reboot
5. confirm sound is working
....
v. install plugin
w. confirm sound is still working
x. set detent action for rotary encoder 1
y. save
z. no sound

**Comment by pkozlovskiy** [comment]
I have the same problem( on http://www.suptronics.com/miniPCkits/x5000.html
No sound after connect to gpio.

**Comment by psasin** [comment]
I've got same issue. Using Hifi Amp and KY-040 same configuration as @hailogugo .
If I configure 1st encoder for volume control, then it is working fine, but as soon as I configure 2nd encoder for playback control i have no sound. I need to disable 2nd encoder and restart volumio.

Configuration of first encoder (working):
- CLK pin = 23
- DT pin = 25
- SW pin = 23
- Coding = Default
- Detent Action = Control Volume
- Button Action = Toggle mute/unmute

Configuration of second encoder (no sound after setting)
- CLK pin = 19
- DT pin = 26
- SW pin = 13
- Coding = Default
- Detent Action = Media Control
- Button Action = Toggle play/pause

Volumio version 2.378

**Comment by Saiyato** [comment]
Ok, for my understanding, the problem occurs only when you install a second encoder?
Have you configured the same pin for CLK and SW on the first encoder?

Also, the documentation of both the Suptronics and Hifiberry contain detailed descriptions of the GPIO pins you can't use, 19 being one of them ;) Pins 18-21 are normally used for the sound interface, so you can't use them for anything else if you want to boards to work.

HifiBerry: https://www.hifiberry.com/build/documentation/gpio-usage-of-hifiberry-boards/
Suptronics: http://www.suptronics.com/miniPCkits/x5000.html

I trust this will solve your problems, if not I can re-open the issue. 

@psasin this means your second encoder can't use pin 19 for CLK.
