### ISSUE TITLE
I need some help with this.

### ISSUE THREAD

**Issue by popracer** [Saiyato/volumio-rotary-encoder-plugin#7]
I must be doing something very wrong, I put the clock to gpio17 and the dt to gpio18 on a rotary encoder with breakout. I set it to the pins and it doesnt do anything really, it just turns the volume down and doesnt do anything after that. Im using a pi zero w. is that why it won't work? am I using the wrong pins?

**Comment by Saiyato** [comment]
Plase see issue #5 , are you using a separate soundcard? Because pin 18 is used by most external cards.

Other than that I see no reason why it shouldn't work, have you used the last version (from GitHub)?
