### ISSUE TITLE
Unable to get it working

### ISSUE THREAD

**Issue by LordorKat** [Saiyato/volumio-rotary-encoder-plugin#8]
Hi. Nice plugin but  I'm unable to get the version on github working. I have RPi 3 B with volumio 2.413.
Npm install goes fine:
`volumio@volumio:~/volumio-rotary-encoder-plugin$ volumio plugin install

This command will install the plugin on your device

Compressing the plugin
No modules found, running "npm install"
npm notice created a lockfile as package-lock.json. You should commit this file.
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin
Progress: 30
Status :Creating folder on disk
Progress: 40
Status :Unpacking plugin
Progress: 50
Status :Checking for duplicate plugin
Progress: 60
Status :Copying Plugin into location
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 90
Status :Adding plugin to registry
Progress: 100
Status :Plugin Successfully Installed
Done!`

I can see the plugin on the GUI but the it will not start. The gui says: This plugin is failing to start.
When traying to activate it:

`volumio@volumio:/data/plugins/user_interface/rotaryencoder$ sudo journalctl -f
-- Logs begin at Sat 2018-07-21 05:30:33 UTC. --
Jul 21 05:40:42 volumio volumio[879]: info: Enabling plugin rotaryencoder
Jul 21 05:40:42 volumio volumio[879]: info: Loading plugin "rotaryencoder"...
Jul 21 05:40:42 volumio volumio[879]: error: !!!! WARNING !!!!
Jul 21 05:40:42 volumio volumio[879]: error: The plugin user_interface/rotaryencoder failed to load, setting it to stopped. Error: SyntaxError: Unexpected token ;
Jul 21 05:40:42 volumio volumio[879]: error: !!!! WARNING !!!!
Jul 21 05:40:42 volumio volumio[879]: info: Error: TypeError: Cannot read property 'printToastMessage' of null
`

After reboot the GUI is inaccessible and I have to delete the /data/plugins/user_interface/rotaryencoder directory to get working.  The version on Volumio shop is working ok when installed from the GUI. 

Any advice?

**Comment by superjasiek** [comment]
Same here - struggling with plugin for a longer time. Also installing from UI freezes Volumio. Running on Pi Zero W with hifiberry DAC +

**Comment by Saiyato** [comment]
Hi there, the latest version is incorporated in the store and should install normally.
